name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: []
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... -timeout 2m
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.go-version == '1.22.x' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
